### ISSUE TITLE
ultraviolet doesnt save cookies

### ISSUE THREAD

**Issue by 3XPLwastaken** [titaniumnetwork-dev/Ultraviolet-App#18]
i just setup ultraviolet on my own server, and it runs perfectly fine, almost. I'm trying to launch parsec.app, but the site does not save cookies. i login but since i have no way to save the auth i instantly am logged out. anyone know how to fix this?

**Comment by e9x** [comment]
Ultraviolet saves cookies, however the website in question may set cookies across JavaScript contexts in a way that prevents cookies from being saved.
