### ISSUE TITLE
it doesnt support now.gg

### ISSUE THREAD

**Issue by jbxskm** [titaniumnetwork-dev/Ultraviolet-App#19]
I cant use https://now.gg/apps/roblox-corporation/5349/roblox.html on this. I remixed this to glitch and it doesnt work.

**Comment by jbxskm** [comment]
Gimme a glitch link once you've made it so I can use now.gg.

**Comment by jose-gonzalez-cool** [comment]
you cant use now.gg on ultraviolet. try doing kxd.fm/roblox instead, although sadly that might have been patched aswell.

**Comment by jbxskm** [comment]
There's got to be a loophole so they can make it now.gg supported.

**Comment by jbxskm** [comment]
kxd.fm/roblox doesnt work
