### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by sourcemaster7** [titaniumnetwork-dev/Ultraviolet-App#20]
Doesnt work says "Failed to register service worker.

ReferenceError: __uv$config is not defined"

## Expected Behavior
Should work

## Current Behavior
Says that

## Possible Solution
How to fix

## Steps to Reproduce

1.Open
2.Search anything
3.
4.

**Comment by e9x** [comment]
you likely didn't copy all the ultraviolet scripts from the release or you have some syntax error in your uv.config.js

**Comment by bachwebsite** [comment]
> you likely didn't copy all the ultraviolet scripts from the release or you have some syntax error in your uv.config.js

what should i put instead of "__uv$config"
