### ISSUE TITLE
Ultraviolet not working on hbomax, disney plus or any movies or serie website.

### ISSUE THREAD

**Issue by aitronz** [titaniumnetwork-dev/Ultraviolet-App#22]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

Ultraviolet Not working on websites of series and movies like netflix, hbomax or disneyplus

## Expected Behavior

Play the movie or serie

## Current Behavior

When you click the play button shows an error 

## Steps to Reproduce

1. Enter the website using ultraviolet
2. Click any serie or film
3. Click the play button
4. Shows an error

hbomax error
![image](https://user-images.githubusercontent.com/74368135/215299448-5acbeddd-d1a2-4ffa-809b-e46b9d39286e.png)

**Comment by Baggette** [comment]
This would most likely be impossible to fix as those sites use drm to protect their content and its not possible with this proxy to bypass that drm IIRC

**Comment by e9x** [comment]
> This would most likely be impossible to fix as those sites use drm to protect their content and its not possible with this proxy to bypass that drm IIRC

Typically DRM is easy to bypass, until the DRM is also in the browser and using JavaScript. These websites not working are likely a sign of most streaming services blocking the use of proxies. They could be flagging the datacenter IP addresses and refusing to serve content to them.
