### ISSUE TITLE
No longer works when remixing on glitch

### ISSUE THREAD

**Issue by Aonperson** [titaniumnetwork-dev/Ultraviolet-App#23]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

was working fine 2 weeks ago

## Expected Behavior

The application should open up and run

## Current Behavior

It is stuck on loading and starting until it give up

cites "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ultraviolet-static' imported from /app/src/index.js"
## Steps to Reproduce

1. just try to remix on glitch
2. open up glitch logs
3. see the issue
4.

## Context (Environment)

Im just trying to watch content without internet tracking.

It no longer runs on glitch.

**Comment by ABUCKY0** [comment]
Know that this isn't like a public VPN. Any requests go to glitch, then are sent to your device. They can trace it to your glitch account. A public service allows for anonymity by mixing traffic together

**Comment by e9x** [comment]
@Aonperson Make sure you're running `npm install`
