### ISSUE TITLE
Deceptive Site Ahead Warning on Discord

### ISSUE THREAD

**Issue by ABUCKY0** [titaniumnetwork-dev/Ultraviolet-App#24]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

Discord should load normally

## Current Behavior

Discord pops up with a Deceptive Site Ahead warning.

## Possible Solution

It is caused possibly by this, so a possible fix would be to enable an optional color shift for affected websites to fool Chrome

## Steps to Reproduce

1. Create the proxy, and navigate to discord.com
2. It should show a deceptive site ahead warning, if not, visit the discord login page

## Context (Environment)

I was trying to log into Discord through a personally run instance of Ultraviolet

## Detailed Description

Loading some sites can cause Chrome to show a phishing page, caused by the phishing engine detector.

## Possible Implementation

Add some sort of optional altered CSS file that goes into effect on affected websites, overwriting the provided CSS file. Some sort of color shift could possibly fix this.

**Comment by ABUCKY0** [comment]
I will say though that I don't have evidence to back up changing the css file will fix it, but if I read the page right and it is matching colors, a css file change should work.

**Comment by e9x** [comment]
I suspect that this behavior is associated with your domain/deployment service. What are you deploying Ultraviolet-App to?

**Comment by ABUCKY0** [comment]
https://render.com

**Comment by BuckleMyShoe147** [comment]
May I ask what server and environment this was deployed to.

**Comment by ABUCKY0** [comment]
I deployed the Ultraviolet App commit (The latest one didn't work) as a Web Service
