### ISSUE TITLE
Deploying on koyeb does not work.

### ISSUE THREAD

**Issue by peacocksir** [titaniumnetwork-dev/Ultraviolet-App#25]
## Summery of the issue

when deploying with koyeb, the deployment process starts off correctly and succeeds but then a little bit after it is marked as unhealthy and does not work

## What should happen 

app deploys, succeeds and is marked as healthy and when visiting the page it is there and works

## what happens instead

app gets deployed, succeeds but then gets marked as unhealthy and visiting the page does not work.

## steps to reproduce

just deploy ultraviolet with koyeb

**Comment by BOZOPOOP** [comment]
yeah

**Comment by xbubbo** [comment]
yeah lol

**Comment by randomconfusedperson** [comment]
i think it may be the TOS thing, idk tho

**Comment by coldlee-en** [comment]
Just do it on cyclic its free and works great

**Comment by e9x** [comment]
probably TOS
