### ISSUE TITLE
Ultraviolet slows down after 1st use.

### ISSUE THREAD

**Issue by proJM-Coding** [titaniumnetwork-dev/Ultraviolet-App#26]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

Ultraviolet runs super fast and great on the first use and should stay that way after the 1st use.

## Current Behavior

Runs super slowed down after 1st use.

## Possible Solution

Is it something to do with the cached files and other cached stuff?

## Steps to Reproduce

Follow steps here: https://github.com/titaniumnetwork-dev/Ultraviolet-App/wiki/Deploy-via-terminal
Note after 1st use it becomes slow.

## Context (Environment)

ultraviolet becomes slow and hard to use.

**Comment by e9x** [comment]
Perhaps it's your host? Does the performance improve when you restart the script on your server?

**Comment by proJM-Coding** [comment]
Once it's restarted it's still slow.

**Comment by proJM-Coding** [comment]
Never mind my host deleted ultraviolet and I can't remake it because it's against their tos
