### ISSUE TITLE
Cannot find Package.

### ISSUE THREAD

**Issue by 7DatsonBack** [titaniumnetwork-dev/Ultraviolet-App#27]
When launched onto replit, cyclic, etc, it gives me a warning**:**

**_Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ultraviolet-static' imported from /var/task/src/index.js._**
It seems it's not able to fetch it and is then stopping.
How can I fix this?

**Comment by 12944qwerty** [comment]
No idea why this suddenly happened... but just replace the package.json dependencies with and then npm i.

```
"dependencies": {
    "@titaniumnetwork-dev/ultraviolet": "^1.0.8-beta",
    "@tomphttp/bare-server-node": "^1.2.3",
    "express": "^4.18.2",
    "ultraviolet-static": "titaniumnetwork-dev/Ultraviolet-Static"
},
```

**Comment by e9x** [comment]
I'm surprised an issue wasn't made sooner... This is due to the package.json referencing a local repo.

**Comment by e9x** [comment]
Fixed.
