### ISSUE TITLE
GFN and Discord don't work.

### ISSUE THREAD

**Issue by Prexry** [titaniumnetwork-dev/Ultraviolet-App#28]
## Expected Behavior

GeForce NOW should load into the selected game
Discord should load.

## Current Behavior

GeForce NOW doesn't load selected games.
Discord displays "Forbidden IP."

## Steps to Reproduce

1. Go to a deployed UV (https://ved.knightcastle.tk)
2. Login and go to play.geforcenow.com
3. Choose any game.
4. Game fails to load.
-- Discord
1. discord.com
2. Forbidden IP

## Context (Environment)

1 month

**Comment by e9x** [comment]
try running your bare server through a proxy or changing hosting providers
this is not a UV issue
