### ISSUE TITLE
Base64 encoding/decoding very buggy unlike Xor encoding/decoding

### ISSUE THREAD

**Issue by SkyTheNerd** [titaniumnetwork-dev/Ultraviolet-App#29]
Base64 encoding/decoding is very buggy, which I currently rely on to achieve some tasks on the project I'm working on.
## Expected Behavior

Everything is stable like it is when the encode/decode is Xor.

## Current Behavior

Errors like these below happen frequently and search engines like google don't work.
![image](https://user-images.githubusercontent.com/79011616/218609187-5b146c9f-de7b-470b-8244-a27c7e65b575.png)
![image](https://user-images.githubusercontent.com/79011616/218608375-997e7fa7-8b26-4e78-8cb5-7a1a20248f3a.png)
![image](https://user-images.githubusercontent.com/79011616/218609256-73c9c38b-2017-40bd-a6ce-de67b702b536.png)

## Steps to Reproduce
Live Example: https://bb-base-node-v2.skyatschool.repl.co/

Change the uv.config.js file in frontend to encode/decode URLs as base64

## Context (Environment)

I have been working on a small project for bypassing GoGuardian called [Bunker Browser](https://github.com/SkyTheNerd/Bunker-Browser/) (Live demo [here](https://bunkerbrowserdemo.ga)) and there is a feature where you can search using the Ultraviolet proxy. Recently, it hasn't been working because iframes stopped working because the way I did it was using repl.it, and I was using the temporary link that is iframed for the workspace. I wanted to use the actual link for it but it wasn't working in iframes so I updated my Ultraviolet to the latest version. The way I made the search work for Bunker Browser is by taking what is searched in the search bar and encoding it with base64 because I don't know how to work with xor.

## Detailed Description

The change I would like is to make base64 more stable, but an alternative way is to figure out a solution to do my encoding for my proxy search function so it works with xor encoding. (Base64 also kind of sucks because the lightspeed filter still blocks everything on school windows devices)

**Comment by SkyTheNerd** [comment]
Ok, I found out why search engines don't work, it's because the search variable is not encoded when searching, causing invalid results.
![Screenshot_20230214_064422](https://user-images.githubusercontent.com/79011616/218888355-39516dac-76ca-4233-98cb-920f5cdf567a.png)

**Comment by ProgrammerIn-wonderland** [comment]
Complete sidenote but should be noted that using base64 increases bandwidth usage and is likely slower in everything other than encode/decode steps, your network throughput will likely be 2/3rds of Xor, just a fair warning
