### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nyveii12bigbro** [titaniumnetwork-dev/Ultraviolet-App#32]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

 when i go onto to mske one it ethire says it cant do it or it says 404 error

## Expected Behavior

 FIXXX IT

## Steps to Reproduce

1.
2.
3.
4.

**Comment by BRUHGMAISNJDFIAs** [comment]
I used it and it does work, what's your problem?

**Comment by CatMan6112** [comment]
his problem was autism
