### ISSUE TITLE
replit missing "start" script

### ISSUE THREAD

**Issue by Crosshairs2** [titaniumnetwork-dev/Ultraviolet-App#33]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by LU5ive** [comment]
i would recommend using ultraviolet-app and not ultraviolet

https://github.com/titaniumnetwork-dev/Ultraviolet-App

**Comment by LU5ive** [comment]
try reforking

**Comment by LU5ive** [comment]
if it doesnt work try doing it on cyclic

**Comment by e9x** [comment]
but we have a start script! it's right here: https://github.com/titaniumnetwork-dev/Ultraviolet-App/blob/4cc65b1d9f919dbcf6e07581ac46b8d4a2e05725/package.json#L11

are you sure you followed the instructions correctly?
are you deploying the right repository (Ultraviolet-App)?
