### ISSUE TITLE
Error Processing your request

### ISSUE THREAD

**Issue by dlee2009** [titaniumnetwork-dev/Ultraviolet-App#36]
So I am hosting the ultraviolet on github codespaces, but the proxy wont work. I am using the port=8080, and followed all the steps for via terminal(Used codespace's terminal) Take a look at the screenshot below and help me troubleshoot this please. Thank you !
![Screenshot 2023-02-22 7 51 02 AM](https://user-images.githubusercontent.com/68925893/220639619-64eeeb83-65cf-4b74-bff3-df9c044f375d.png)

**Comment by kurbus** [comment]
this appears to be an issue with commit 60a168a55b3e166b68c745803520364229e79839 , had this same issue

**Comment by e9x** [comment]
I was able to clone this repository locally and start UV-app without any issues. I highly doubt the commit you chose is relevant to this. I suspect GitHub codespaces has a convoluted way of authenticating you (because they need to keep the codespace private from other users).

**Comment by kurbus** [comment]
> I was able to clone this repository locally and start UV-app without any issues. I highly doubt the commit you chose is relevant to this. I suspect GitHub codespaces has a convoluted way of authenticating you (because they need to keep the codespace private from other users).

i used code sandbox, i think it was a dreaded NPM thing, using the wrong version of bare-server

**Comment by incognitotgt** [comment]
> I was able to clone this repository locally and start UV-app without any issues. I highly doubt the commit you chose is relevant to this. I suspect GitHub codespaces has a convoluted way of authenticating you (because they need to keep the codespace private from other users).

Yep. I got it to work by making the forwarded port public. 
Can we close this @e9x and add it to the wiki?

**Comment by kurbus** [comment]
github pages does some really weird stuff when it comes to http hosting, just use Replit or selfhost if you're not poor

**Comment by incognitotgt** [comment]
1. It's not pages. Codespaces are better than replit for the short term tbh
2. I don't really use it. (self host for my friends)

**Comment by kurbus** [comment]
> 1. It's not pages. Codespaces are better than replit for the short term tbh
> 
> 2. I don't really use it. (self host for my friends)

yeah, i meant codespaces. easily mistaken 

replit is pretty wacky at times, especially with their active hatred for Titanium, and also their got system is fubar

**Comment by incognitotgt** [comment]
wait what
i commented in this issue before i was a real developer lool

**Comment by funkymokey** [comment]
> wait what i commented in this issue before i was a real developer lool

wow super sigma
