### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by 3kh0** [titaniumnetwork-dev/Ultraviolet-App#4]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

the discord main website should show

## Current Behavior

I get an error, `TypeError: Failed to fetch`

![image](https://user-images.githubusercontent.com/58097612/193864911-a198fb86-e2d7-4eba-af83-8b881e0441e4.png)

## Possible Solution

[🤷‍♂️](https://emojipedia.org/man-shrugging/)

## Steps to Reproduce

1. https://purple-chicken.3kh0.repl.co/ 
2. put in discord.com/app

## Context (Environment)

hosted on replit, this happens for anything you put in the box

## Detailed Description

Not much to say here, nothing was showing up in console

## Possible Implementation

🤷‍♂️ make more detailed error messages might help

**Comment by desplmfao** [comment]
is your node.js version above v14

**Comment by MotorTruck1221** [comment]
> is your node.js version above v14

This is happening to me as well with node.js v18.

> the discord main website should show

This is also not just a discord issue. This happens when I try and use any website at all.

**Comment by 3kh0** [comment]
node.js is v18

**Comment by e9x** [comment]
This is likely a clone of #6. Perhaps you can take the same steps I recommended to help me understand the problem.
