### ISSUE TITLE
SyntaxError: Unexpected token - when using docker and reverse proxy

### ISSUE THREAD

**Issue by CodingCody-1** [titaniumnetwork-dev/Ultraviolet-App#43]
## Expected Behavior

Site should load

## Current Behavior
I get this error: 
```
SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
```

## Steps to Reproduce

1. Clone the repo
2. Add `version: "3"` to the top of the docker-compose
3. Spin up container
4. Use nginx reverse proxy on another server to add SSL and a domain
5. Go to any link

## Context (Environment)

Running on Docker on Ubuntu 20.04. Using nginx-reverse-proxy and Cloudflare for DNS.

**Comment by calcossmonkey** [comment]
yea i think this is happening to everyone right now i think this is a problem on ultraviolets side. 
SyntaxError: Unexpected token < in JSON at position 0
even on my home computer im getting this error, I think that something internal is causing this error..

**Comment by CodingCody-1** [comment]
Are you running a setup similar to mine? I think the issue is that I am not connecting to it over localhost. Instead I am using the IP address of the server.

**Comment by CodingCody-1** [comment]
I fixed my issue! I needed to disable basic password auth in Nginx. See [here](https://github.com/titaniumnetwork-dev/Ultraviolet/issues/41).
