### ISSUE TITLE
Error processing your request

### ISSUE THREAD

**Issue by matti377** [titaniumnetwork-dev/Ultraviolet-App#49]
I Installed The VPN on an VPS with an public ip (ubuntu server). It is running in the background with pm2 (I did everything like it was explained in the wiki). When I enter an url, for example google.com I get this:
![Screenshot 2023-04-23 at 10 56 48](https://user-images.githubusercontent.com/119162325/233830078-29ed90c1-c94f-421c-9429-205f5ae07ad8.png)
Does somebody know how to fix this?

**Comment by Bigfoot9999** [comment]
You have to have a bare server running or change the settings in uv.config.js.

**Comment by matti377** [comment]
wat do I need to change? Here is my file:


self.__uv$config = {
  prefix: "/uv/service/",
  bare: "/bare/",
  encodeUrl: Ultraviolet.codec.xor.encode,
  decodeUrl: Ultraviolet.codec.xor.decode,
  handler: "/uv/uv.handler.js",
  client: "/uv/uv.client.js",
  bundle: "/uv/uv.bundle.js",
  config: "/uv/uv.config.js",
  sw: "/uv/uv.sw.js",
};

**Comment by C-1-R** [comment]
I've got the same problem. It was working fine just a week ago. When I go to the bare server it says the following:
{
	"versions": [
		"v1",
		"v2"
	],
	"language": "NodeJS",
	"memoryUsage": 10.82,
	"project": {
		"name": "bare-server-node",
		"description": "TOMPHTTP NodeJS Bare Server",
		"repository": "https://github.com/tomphttp/bare-server-node",
		"version": "1.2.5"
	}
}
Does this have anything to do with the problem?

**Comment by PotatoLord1234** [comment]
Hey, the same thing is happening to me. Did you ever figure it out?

**Comment by Notplayingallday383** [comment]
kind of weird but maybe Update UV and Bare cus v1.2.5 of Bare isnt the latest 2.0.1 is and for UV 2.0.0 is the latest or v1.0.11 if u need bare v2 so yea prob update that and try again

**Comment by Praveit** [comment]
How do I update it?

**Comment by BeyYT** [comment]
if you are using an NGINX reverse proxy, try updating the [buffer sizes.](https://github.com/titaniumnetwork-dev/Ultraviolet-App/wiki/Configure-SSL#approach-2-reverse-proxy-nginx)

**Comment by Deovolentezz** [comment]
I have the same problem,  how to solve it?
