### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by ghost** [titaniumnetwork-dev/Ultraviolet-App#50]
codesandbox request error when i deploy. please do not give me a hard explanation, i wont understand.

bare server: {
	"versions": [
		"v1",
		"v2"
	],
	"language": "NodeJS",
	"memoryUsage": 9.01,
	"project": {
		"name": "bare-server-node",
		"description": "TOMPHTTP NodeJS Bare Server",
		"repository": "https://github.com/tomphttp/bare-server-node",
		"version": "1.2.5"
	}
}
![error image](https://user-images.githubusercontent.com/129239408/236557960-88ae23af-f37d-4d00-97a6-a201c017aa68.png)

**Comment by e9x** [comment]
there will be no explanation 
deploy to a different service
