### ISSUE TITLE
When I deploy on render or glitch does not work

### ISSUE THREAD

**Issue by Ljduley12** [titaniumnetwork-dev/Ultraviolet-App#53]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Thesecondalthowcool** [comment]
I had the same issue. But for some reason, using a docker version works. Just use https://github.com/Thesecondalthowcool/Ultraviolet-Docker and run the dockerfile in it

**Comment by Thesecondalthowcool** [comment]
You can also use the build and start commands npm install and npm run start

**Comment by Ljduley12** [comment]
Ok Just asking Would you know the way you could make it so you could play roblox

**Comment by Thesecondalthowcool** [comment]
1. skid 2. dont know, use astroid proxy
