### ISSUE TITLE
Deploying not working

### ISSUE THREAD

**Issue by the-potato-1** [titaniumnetwork-dev/Ultraviolet-App#54]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
Deploying works with no problems

## Current Behavior
Project gets suspended, banned, etc. because of violation of ToS

## Possible Solution
Make it not violate ToS

## Why it's not working
Violation of Terms of Service

## Steps to Reproduce

1. Follow any of the instructions to deploy to project to a service (Replit, Glitch, Railway, etc.)

## What i'm trying to do

I am trying to customize the front Ultraviolet page

**Comment by Thesecondalthowcool** [comment]
What deployment service are you on?

**Comment by Ljduley12** [comment]
If your trying to edit change static file index HTML but for like replit and glitch for you use those sometimes they flag you

**Comment by Thesecondalthowcool** [comment]
it's prob because of the bare server on it. And maybe they have a data base of what things aren't allowed like UV images

**Comment by 2023SMHrailwaygames** [comment]
would i get banned on railway since this is a mirror/userbot

**Comment by 2023SMHrailwaygames** [comment]
yes you would unless you change something like make it say nothing and no images prob wrk

**Comment by e9x** [comment]
skibidi toilet
