### ISSUE TITLE
dependency resolve errors on npm install

### ISSUE THREAD

**Issue by Ghxst** [titaniumnetwork-dev/Ultraviolet-App#56]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

`npm install` without errors or requirement of `--force`

## Current Behavior

`npm install` fails with some resolve / dependency errors
https://gist.github.com/Ghxst/f39a322bcfba0d1a95ef8830c02df3ce

## Possible Solution

the conflicts need to be resolved or docs need to be updated

## Steps to Reproduce

1. `git clone https://github.com/titaniumnetwork-dev/Ultraviolet-App.git`
2. `cd Ultraviolet-App`
3. `npm install`

instructions from
https://github.com/titaniumnetwork-dev/Ultraviolet-App/wiki/Deploy-via-terminal

## Context (Environment)

Following the docs result in a failure to deploy locally and I am unable to get Ultraviolet-App to run without `--force`.
When using `--force` the install is successful (although with conflicts) but then I am running into issues that I can't diagnose properly.

**Comment by e9x** [comment]
thanks. this was because this repository uses an outdated version of ultraviolet-static. we can install the latest one to fix this issue.

**Comment by e9x** [comment]
See https://github.com/titaniumnetwork-dev/Ultraviolet-App/commit/c36f37d92440dc2f422d4770b4efa478905fcee4

**Comment by Ghxst** [comment]
Thank you! 🙌
