### ISSUE TITLE
Youtube doesn't work anymore

### ISSUE THREAD

**Issue by fluffyball9** [titaniumnetwork-dev/Ultraviolet-App#57]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

When I open YouTube and click on a video, it tells me "Connect to the internet. You're offline. Check your connection."

## Expected Behavior

It should open the video that I clicked on.

## Current Behavior

It says "Connect to the internet. You're offline. Check your connection."

## Steps to Reproduce
1. open youtube.com in ultraviolet
2. click on a video link

**Comment by np22-jpg** [comment]
This is probably something Google added to YouTube recently, because builds as far back as 3 months ago do not work anymore.

**Comment by np22-jpg** [comment]
It appears to work for me again now on my docker images. Has it been fixed for you?

**Comment by fluffyball9** [comment]
Yes, it's working now.
