### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by non-reai** [titaniumnetwork-dev/Ultraviolet-App#66]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

There shouldn't be a memory leak. This memory leak may be the reason that Ultraviolet keeps closing.

## Current Behavior

There is a memory leak (No idea where)

## Possible Solution

Use emitter.setMaxListeners() to increase limit

## Steps to Reproduce

1. Start Ultraviolet-App
2. Wait until it warns

## Context (Environment)

I am hosting Ultraviolet-App on my Raspberry Pi 2b and sometimes the webserver closes randomly.

## Detailed Description

Fix the issue?

## Possible Implementation

Don't know.

**Comment by non-reai** [comment]
There is also this: 
![image](https://github.com/titaniumnetwork-dev/Ultraviolet-App/assets/63729314/d9c5dbb5-3245-4b51-b516-8cf46b8c7729)

**Comment by non-reai** [comment]
![image](https://github.com/titaniumnetwork-dev/Ultraviolet-App/assets/63729314/32016fbc-1576-46b0-b86a-0e5a0e29fb71)

**Comment by non-reai** [comment]
im on 32 bit os if that helps

**Comment by funkymokey** [comment]
skill issue

**Comment by non-reai** [comment]
Wow! That was really creative and insightful to my bug report, thanks!

**Comment by funkymokey** [comment]
your welcome
