### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by smikkelbakje** [titaniumnetwork-dev/Ultraviolet-App#7]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
website would search things

## Current Behavior
doesnt search the thing i want because of a javascript error

## Steps to Reproduce

1. install UV
2. try searching something
3. in webconsole it spits errors out when i press enter
4.

## Detailed Description
the host is  Ubuntu 22.04.1 LTS x86_64
npm version 8.19.2

![image](https://user-images.githubusercontent.com/59176120/198736364-ef2a8192-1c8c-4c29-8354-a8ef6ff20f46.png)
![image](https://user-images.githubusercontent.com/59176120/198736690-ee810f92-3b69-4ab8-9f19-fdd57a322067.png)

**Comment by e9x** [comment]
What version of chrome are you running? It looks like navigator.serviceWorker is undefined.

**Comment by smikkelbakje** [comment]
![image](https://user-images.githubusercontent.com/59176120/198740013-3120c138-2057-4ec8-9daf-e7f0e7c52a59.png)

**Comment by smikkelbakje** [comment]
i can also try it on edge and it does the same thing
![image](https://user-images.githubusercontent.com/59176120/198740128-a1b795f4-b282-47d4-9107-0e87782b9924.png)

**Comment by e9x** [comment]
Ah, then it must be because you're missing SSL. SSL or HTTPS is required for service workers to be registered. This repository assumes you setup SSL yourself or a deploy service did for you.

**Comment by smikkelbakje** [comment]
tried launching it on port 80 or 443 to proxy it trough cloudflare but it refuses to launch
![image](https://user-images.githubusercontent.com/59176120/198740721-8dfe6cf9-ad33-4778-9e12-7b091f0b127f.png)

**Comment by smikkelbakje** [comment]
already fixed it on my own it stopped complaining

**Comment by smikkelbakje** [comment]
yep now it seems to work

**Comment by e9x** [comment]
> tried launching it on port 80 or 443 to proxy it trough cloudflare but it refuses to launch ![image](https://user-images.githubusercontent.com/59176120/198740721-8dfe6cf9-ad33-4778-9e12-7b091f0b127f.png)


- something is listening on port 443
- windows needs your permission to listen on port 443

btw, it will listen on http without encryption on port 443 which is unintended..
you will need to patch this repository to use the https module and call createServer with your SSL cert data

cloudflare is a much easier solution
