### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by thedogecraft** [titaniumnetwork-dev/Ultraviolet-App#71]
Error : Failed to register service worker.

TypeError: Failed to register a ServiceWorker for scope ('http://localhost:8080/uv/service/') with script ('http://localhost:8080/uv/sw.js'): An unknown error occurred when fetching the script.

i have not touched anything i cloned it and npm install and npm start

**Comment by Zernic** [comment]
having same problem

**Comment by QuiteAFancyEmerald** [comment]
Should be resolved ensure you are testing in Chrome
