### ISSUE TITLE
Online games such as 1v1.lol do not connect to the internet.

### ISSUE THREAD

**Issue by itamar1238** [titaniumnetwork-dev/Ultraviolet-App#73]
## Expected Behavior

When using 1v1.lol or any other online website, you should be able to connect to their online play and play with other users.

## Current Behavior

When going onto 1v1.lol and other sites like it, it says please check that youŕe connected to the internet and wont let me play multiplayer.

## Possible Solution

I keep seeing in the dev console, ¨wss://domain.whatever/bare/v3¨ refused to connect. Could be the reason.

## Steps to Reproduce

1. Go onto 1v1.lol with the proxy and try to play.

How can I fix this?

**Comment by leahanderson1** [comment]
it appears that websockets do not work for some reason. I'll look into it.
