### ISSUE TITLE
iFrame instead of redirect

### ISSUE THREAD

**Issue by SchoolTARMaster** [titaniumnetwork-dev/Ultraviolet-App#75]
So, I am trying to make my own frontend for UV, and I am currently using the Ultraviolet-App backend and Ultraviolet-Static frontend. I want to make it so that when I type a URL, it creates an iFrame element of the result, instead of redirecting me. Anybody has an idea on how to do so ?

**Comment by non-reai** [comment]
load the entire homepage into an iframe

**Comment by SchoolTARMaster** [comment]
I don't wanna do that, looking for a different solution
