### ISSUE TITLE
there are no bare clients

### ISSUE THREAD

**Issue by 06NinjaKid06** [titaniumnetwork-dev/Ultraviolet-App#82]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
To connect to local host, type in an link, and it work.

## Current Behavior
I type in a link, it has to register service worker, so i do that, and it says "Your organization has blocked access to this page or site." (if i follow the link from the failed HTTP GET response, it says 
```
<h1 id="errorTitle">Error processing your request</h1><hr><p>Failed to load <b id="fetchedURL">https://www.google.com/search?q=bing</b></p><p id="errorMessage">Internal Server Error</p>
Code: | UNKNOWN
-- | --


<textarea id="errorTrace" cols="40" rows="10" readonly="readonly"></textarea><p>Try:</p><ul><li>Checking your internet connection</li><li>Verifying you entered the correct address</li><li>Clearing the site data</li><li>Contacting <b id="uvHostname">localhost</b>'s administrator</li><li>Verify the <a id="bareServer" title="Bare server" href="http://localhost:8080/bare/">Bare server</a> isn't censored</li></ul><p>If you're the administrator of <b id="uvHostname">localhost</b>, try:</p><ul><li>Restarting your Bare server</li><li>Updating Ultraviolet</li><li>Troubleshooting the error on the <a href="https://github.com/titaniumnetwork-dev/Ultraviolet" target="_blank">GitHub repository</a></li></ul><hr><p><i>Ultraviolet v<span id="uvVersion">3.0.0</span></i></p>Error processing your request

Failed to load https://www.google.com/search?q=bing

Internal Server Error
Code:	UNKNOWN
            there are no bare clients
Try:

    Checking your internet connection
    Verifying you entered the correct address
    Clearing the site data
    Contacting localhost's administrator
    Verify the [Bare server](http://localhost:8080/bare/) isn't censored

If you're the administrator of localhost, try:

    Restarting your Bare server
    Updating Ultraviolet
    Troubleshooting the error on the [GitHub repository](https://github.com/titaniumnetwork-dev/Ultraviolet)

Ultraviolet v3.0.0
```

## Possible Solution

I am asking for the fix, so no response.

## Steps to Reproduce

1. connect to localhost:8080 after following the "Deploy via terminal" wiki
2. type in a link
3. register service worker
4. get page blocked
5. redo steps 1-4 except while inspect is open
6. follow HTTP GET link
7. get error.

## Context (Environment)

I am on firefox, i am hosting using a Raspberry Pi 4B, and if this doesn't get fixed i can't use Ultraviolet :(
also the bare server just gives me an error saying ultraviolet doesn't know where to put me

## Detailed Description

Need a fix, I have no idea.

## Possible Implementation

need a fix, no idea

**Comment by Notplayingallday383** [comment]
This should be fixed in the latest site update

**Comment by Aydendoane** [comment]
same issue today on jordans math work v7

**Comment by 3220-eng** [comment]
383092

**Comment by 3220-eng** [comment]
I GOT HEELLA MONEY

**Comment by 3220-eng** [comment]
bitch

**Comment by 3220-eng** [comment]
we do not care about jordan

**Comment by e9x** [comment]
> I GOT HEELLA MONEY

So true king

**Comment by e9x** [comment]
Just go find your own client.
