### ISSUE TITLE
Gitpod deployment doesn't work.

### ISSUE THREAD

**Issue by catfoolyou** [titaniumnetwork-dev/Ultraviolet-App#85]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

The proxy should work normally

## Current Behavior

When I deploy the proxy via Gitpod, I'm getting a blank grey page with text `8080-catfoolyou-ultravioleta-6kybl5it3v7.ws-us110.gitpod.io refused to connect.` on it when trying to open a URL through the deployed proxy.

## Possible Solution

Register service workers? No option to do that though...

## Steps to Reproduce

Go to (gitpo.io/#https://github.com/titaniumnetwork-dev/Ultraviolet-App)[gitpo.io/#https://github.com/titaniumnetwork-dev/Ultraviolet-App]

Set up the workspace then make the port public and open it.

## Context (Environment)

I can't use the proxy and have to use Incognito instead, but that cant download files and gives me a bunch of gibberish instead.

**Comment by funkymokey** [comment]
use vercel :D

**Comment by Scaratech** [comment]
make sure you set the port as open

**Comment by catfoolyou** [comment]
I did

**Comment by catfoolyou** [comment]
Got it fixed with the latest update
