### ISSUE TITLE
Bug: build through Koyeb fails saying, "! A pnpm lockfile (`pnpm-lock.yaml`) was detected, but the ! version of `pnpm` to install could not be determined."

### ISSUE THREAD

**Issue by FunnyDoggs** [titaniumnetwork-dev/Ultraviolet-App#87]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
I though it would deploy fine.
## Current Behavior
It fails when trying to use a pnpm version.
## Possible Solution
I don't really know
## Steps to Reproduce

1.Deploy on Koyeb
2.Wait for the build to fail.
3.
4.

#LOG
Build ready to start ▶️
>> Cloning github.com/titaniumnetwork-dev/Ultraviolet.git commit sha a70f303e291b360095878fa059f67d6bc709d96b into /workspace
Initialized empty Git repository in /workspace/.git/
From https://github.com/titaniumnetwork-dev/Ultraviolet
 * branch            a70f303e291b360095878fa059f67d6bc709d96b -> FETCH_HEAD
HEAD is now at a70f303 chore: bump version
Previous image with name "registry01.prod.koyeb.com/k-88eeffcb-266f-4ada-89f8-c296750bd14d/c7a175b7-ca21-4901-8a40-3dfa9226b972:latest" not found
3 of 4 buildpacks participating
heroku/nodejs-engine       2.6.2
heroku/nodejs-pnpm-engine  2.6.2
heroku/nodejs-pnpm-install 2.6.2
Layer cache not found
[Heroku Node.js Engine Buildpack]
[Checking Node.js version]
Node.js version not specified, using 20.x
Resolved Node.js version: 20.10.0
[Installing Node.js distribution]
Downloading Node.js 20.10.0
Extracting Node.js 20.10.0
Installing Node.js 20.10.0
- Debug info
  - Corepack Requirement Error
! A pnpm lockfile (`pnpm-lock.yaml`) was detected, but the
! version of `pnpm` to install could not be determined.
!
! `pnpm` may be installed via the `heroku/nodejs-corepack`
! buildpack. It requires the desired `pnpm` version to be set
! via the `packageManager` key in `package.json`.
!
! To set `packageManager` in `package.json` to the latest
! `pnpm`, run:
!
! `corepack enable`
! `corepack use pnpm@*`
!
! Then commit the result, and try again.
ERROR: failed to build: exit status 1
exit status 51

**Comment by FunnyDoggs** [comment]
I just realized, I am cloning the wrong repo.

**Comment by FunnyDoggs** [comment]
oops

**Comment by FunnyDoggs** [comment]
Build ready to start ▶️
>> Cloning github.com/titaniumnetwork-dev/Ultraviolet-App.git commit sha a56e8a315c916d8c8f1fd1fdbd8418d32eb8947a into /workspace
Initialized empty Git repository in /workspace/.git/
From https://github.com/titaniumnetwork-dev/Ultraviolet-App
 * branch            a56e8a315c916d8c8f1fd1fdbd8418d32eb8947a -> FETCH_HEAD
HEAD is now at a56e8a3 Merge pull request #83 from Percslol/main
Previous image with name "registry01.prod.koyeb.com/k-88eeffcb-266f-4ada-89f8-c296750bd14d/4a951091-218d-4f00-88f2-e75335efa062:latest" not found
3 of 4 buildpacks participating
heroku/nodejs-engine       2.6.2
heroku/nodejs-pnpm-engine  2.6.2
heroku/nodejs-pnpm-install 2.6.2
Layer cache not found
[Heroku Node.js Engine Buildpack]
[Checking Node.js version]
Detected Node.js version range: >=16.0.0
Resolved Node.js version: 21.5.0
[Installing Node.js distribution]
Downloading Node.js 21.5.0
Extracting Node.js 21.5.0
Installing Node.js 21.5.0
- Debug info
  - Corepack Requirement Error
! A pnpm lockfile (`pnpm-lock.yaml`) was detected, but the
! version of `pnpm` to install could not be determined.
!
! `pnpm` may be installed via the `heroku/nodejs-corepack`
! buildpack. It requires the desired `pnpm` version to be set
! via the `packageManager` key in `package.json`.
!
! To set `packageManager` in `package.json` to the latest
! `pnpm`, run:
!
! `corepack enable`
! `corepack use pnpm@*`
!
! Then commit the result, and try again.
ERROR: failed to build: exit status 1
exit status 51

**Comment by dwadops** [comment]
> I just realized, I am cloning the wrong repo.

Did you get it to work? I'm having the same issue with koyeb.

**Comment by ge2009** [comment]
```
npm install -g corepack
corepack use pnpm@8.15.4
pnpm install
```
do these action , the problem will get resolved!
