### ISSUE TITLE
Websockets do not work.

### ISSUE THREAD

**Issue by itamar1238** [titaniumnetwork-dev/Ultraviolet-App#96]
The proxy barely works. All you can do is search google. If you try to play any games, they can never connect.

Tested websocketstest.com, and websockets do not work :(

**Comment by Scaratech** [comment]
![image](https://github.com/user-attachments/assets/067426f6-c295-450f-b81e-38f90c7f2bae)
pretty sure it does

**Comment by sharesitedev** [comment]
> ![image](https://private-user-images.githubusercontent.com/153395462/360170139-067426f6-c295-450f-b81e-38f90c7f2bae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODU5ODEsIm5iZiI6MTcyNDI4NTY4MSwicGF0aCI6Ii8xNTMzOTU0NjIvMzYwMTcwMTM5LTA2NzQyNmY2LWMyOTUtNDUwZi1iODFlLTM4ZjkwYzdmMmJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwMDE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGEwMjA2ZTM2MDI0NjlkYzk2ZmNlMTQyZjZlZTk3NjQwYWVlYWU2NmMxOGNmOGI4ZDFhZjA3M2YzM2EyNjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xZqgcQjr0Qdj6WOXXEFcXsF9jcJKxOutoooQvRKTV8U) pretty sure it does

weird. im gonna reinstall the latest and see if it works for me.

**Comment by sharesitedev** [comment]
> ![image](https://private-user-images.githubusercontent.com/153395462/360170139-067426f6-c295-450f-b81e-38f90c7f2bae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODYwNjcsIm5iZiI6MTcyNDI4NTc2NywicGF0aCI6Ii8xNTMzOTU0NjIvMzYwMTcwMTM5LTA2NzQyNmY2LWMyOTUtNDUwZi1iODFlLTM4ZjkwYzdmMmJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwMDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTVkN2Y1ODQ0MDc5NTZjMjU5MzY3OTNjYmM5ZTYwMzQyMGUzZmE4NDUzYTEyNDhmYmRkZjE2Zjg5YTY3ZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OZlai4EnHfruFY-zhWmGsfVJMr7DEg9MjiZEZqvBBzw) pretty sure it does

alr now im getting that they work but I still cant use multiplayer games.
